#!/usr/bin/env python3
"""Auto-generate JS constants file from project/_curated/ filesystem.

Run from project root after Phase B' curation. Re-run anytime user moves
or renames files in _curated/ — the browser composition uses photos_data.js
as its single source of truth for photo paths.

Usage:
    python3 photos_data_gen.py [project_dir]

Default project_dir is "project". Output: <project_dir>/scenes/photos_data.js
"""
import os
import sys
import json

PROJECT = sys.argv[1] if len(sys.argv) > 1 else 'project'

# Adjust BLOCKS to your project's storyboard. Each value is the path of the
# block folder relative to PROJECT/. The keys (block1...block6) become JS
# object keys consumed by scenes_full.jsx.
BLOCKS = {
    'block1': '_curated/block1_xxx',
    'block2': '_curated/block2_xxx',
    'block3': '_curated/block3_xxx',
    'block4': '_curated/block4_xxx',
    'block6': '_curated/block6_xxx',
}

# Optional: a flat list of block6 photos (used as floating "ghost" photos
# in block5's path-integral scene, per the 02 级 design).
GHOST_BLOCK = 'block6'

# Optional: scan project/photos/evo_*.jpg for the post-grad timeline
EVO_DIR_NAME = 'photos'
EVO_PREFIX = 'evo_'


def main():
    out_lines = []
    out_lines.append("// AUTO-GENERATED by photos_data_gen.py from project/_curated/ — do not edit by hand.\n")

    out_lines.append("const PHOTOS = {")
    for key, blk_path in BLOCKS.items():
        full = os.path.join(PROJECT, blk_path)
        out_lines.append(f"  {key}: {{")
        if os.path.isdir(full):
            for sub in sorted(os.listdir(full)):
                sub_path = os.path.join(full, sub)
                if not os.path.isdir(sub_path):
                    continue
                files = sorted([
                    f for f in os.listdir(sub_path)
                    if f.lower().endswith(('.jpg', '.jpeg', '.png'))
                ])
                if not files:
                    continue
                out_lines.append(f"    {json.dumps(sub, ensure_ascii=False)}: [")
                for fn in files:
                    rel = os.path.join(blk_path, sub, fn)
                    out_lines.append(f"      {json.dumps(rel, ensure_ascii=False)},")
                out_lines.append("    ],")
        out_lines.append("  },")
    out_lines.append("};\n")

    # Flat list of ghost-block photos
    if GHOST_BLOCK and GHOST_BLOCK in BLOCKS:
        out_lines.append(f"// Flat list of all {GHOST_BLOCK} photos (used as ghost photos in path-integral scene)")
        out_lines.append(f"const {GHOST_BLOCK.upper()}_FLAT = [")
        ghost_dir = os.path.join(PROJECT, BLOCKS[GHOST_BLOCK])
        if os.path.isdir(ghost_dir):
            for sub in sorted(os.listdir(ghost_dir)):
                sp = os.path.join(ghost_dir, sub)
                if os.path.isdir(sp):
                    for fn in sorted(os.listdir(sp)):
                        if fn.lower().endswith(('.jpg', '.jpeg', '.png')):
                            rel = os.path.join(BLOCKS[GHOST_BLOCK], sub, fn)
                            out_lines.append(f"  {json.dumps(rel, ensure_ascii=False)},")
        out_lines.append("];\n")

    # Evo timeline photos
    evo_path = os.path.join(PROJECT, EVO_DIR_NAME)
    if os.path.isdir(evo_path):
        out_lines.append("const EVO_PHOTOS = [")
        for fn in sorted(os.listdir(evo_path)):
            if fn.startswith(EVO_PREFIX) and fn.lower().endswith(('.jpg', '.jpeg', '.png')):
                year = fn.replace(EVO_PREFIX, '').split('.')[0]
                out_lines.append(f"  {{ src: '{EVO_DIR_NAME}/{fn}', year: {json.dumps(year)} }},")
        out_lines.append("];\n")

    expose = ['PHOTOS']
    if GHOST_BLOCK and GHOST_BLOCK in BLOCKS:
        expose.append(f'{GHOST_BLOCK.upper()}_FLAT')
    if os.path.isdir(evo_path):
        expose.append('EVO_PHOTOS')
    out_lines.append(f"Object.assign(window, {{ {', '.join(expose)} }});")

    output = '\n'.join(out_lines)
    out_file = os.path.join(PROJECT, 'scenes', 'photos_data.js')
    os.makedirs(os.path.dirname(out_file), exist_ok=True)
    with open(out_file, 'w', encoding='utf-8') as f:
        f.write(output)
    print(f"Wrote {out_file}")


if __name__ == '__main__':
    main()
